name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: cd ./frontend

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: |
          node -v
          npm -v
          yarn -v

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build:github

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: build
