name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Show Version
        run: |
          echo node: ${node -v}
          echo npm: ${npm -v}
          echo yarn: ${yarn -v}

      - name: Install
        run: cd ./frontend && yarn --frozen-lockfile

      - name: Build
        run: cd ./frontend && yarn build:github

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: ./frontend/build
